version: "3.5"
services:

  fluent:
    image: "fluentxyz/fluent"
    command:
      - "--chain=dev"
      - "node"
      - "--datadir=/datadir"
      - "--dev"
      - "--full"
      - "--http"
      - "--http.addr=0.0.0.0"
      - "--http.api=eth,net,web3,debug,trace,txpool"
      - "--http.port=8545"
      - "--http.corsdomain=*"
      - "--ws"
      - "--ws.addr=0.0.0.0"
      - "--ws.api=eth,net,web3,debug,trace,txpool"
      - "--ws.port=8546"
      - "--ws.origins=*"
    volumes:
      - "./datadir:/datadir"
    ports:
      - "8545:8545"
      - "8546:8546"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: always

#  blockscout-db:
#    image: postgres:13.6
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: ''
#      POSTGRES_USER: 'postgres'
#      POSTGRES_HOST_AUTH_METHOD: 'trust'
#    volumes:
#      - ./datadir/blockscout:/var/lib/postgresql/data
#    extra_hosts:
#      - 'host.docker.internal:host-gateway'
#    ports:
#      - "7432:5432"
#  blockscout:
#    depends_on:
#      - blockscout-db
#    image: blockscout/blockscout:5.3.2 #4.1.5
#    #image: onthertech/blockscout
#    restart: always
#    links:
#      - blockscout-db:database
#    #command: 'mix do ecto.create, ecto.migrate, phx.server'
#    command: "sleep 100000"
#    extra_hosts:
#      - 'host.docker.internal:host-gateway'
#    environment:
#      ETHEREUM_JSONRPC_VARIANT: "geth"
#      BLOCK_TRANSFORMER: "clique"
#      ETHEREUM_JSONRPC_HTTP_URL: "http://host.docker.internal:8545/"
#      ETHEREUM_JSONRPC_WS_URL: "ws://host.docker.internal:8546/"
#      DATABASE_URL: "postgresql://postgres:@host.docker.internal:7432/blockscout?ssl=false"
#      ECTO_USE_SSL: "false"
#      MIX_ENV: "prod"
#      DISABLE_TOKEN_EXCHANGE_RATE: "true"
#      DISABLE_EXCHANGE_RATES: "true"
#      NETWORK: "Fluent"
#      SUBNETWORK: "Fluent Dev"
#      COIN_NAME: "FLUENT"
#      CHAIN_ID: "1337"
#      JSON_RPC: "https://rpc.dev0.fluentlabs.xyz/"
#    ports:
#      - "4000:4000"

  nginx:
    build: "./nginx"
    environment:
      DOMAIN_NAME: "${DOMAIN_NAME}"
    volumes:
      - /root/.acme.sh/:/root/.acme.sh/
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - "80:80"
      - "443:443"
    restart: always