version: "3.9"

services:
  redis-db:
    extends:
      file: ./services/redis.yml
      service: redis-db

  db-init:
    extends:
      file: ./services/db.yml
      service: db-init

  db:
    depends_on:
      db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/db.yml
      service: db

  backend:
    depends_on:
      - db
      - redis-db
    extends:
      file: ./services/backend.yml
      service: backend
    links:
      - db:database
    environment:
      MICROSERVICE_FLUENT_VERIFIER_URL:
        http://fluent-verifier:8050
        # ETHEREUM_JSONRPC_VARIANT: 'geth'
        # CHAIN_ID: '20993'
        # CHAIN_TYPE: ethereum
    networks:
      - default
      - fluent_net

  visualizer:
    extends:
      file: ./services/visualizer.yml
      service: visualizer

  sig-provider:
    extends:
      file: ./services/sig-provider.yml
      service: sig-provider

  frontend:
    depends_on:
      - backend
    extends:
      file: ./services/frontend.yml
      service: frontend

  stats-db-init:
    extends:
      file: ./services/stats.yml
      service: stats-db-init

  stats-db:
    depends_on:
      stats-db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/stats.yml
      service: stats-db

  stats:
    depends_on:
      - stats-db
      - backend
    extends:
      file: ./services/stats.yml
      service: stats

  user-ops-indexer:
    depends_on:
      - db
      - backend
    extends:
      file: ./services/user-ops-indexer.yml
      service: user-ops-indexer
    networks:
      - default

  proxy:
    depends_on:
      - backend
      - frontend
      - stats
    extends:
      file: ./services/nginx.yml
      service: proxy
    networks:
      - default

  fluent-verifier:
    user: root
    image: ghcr.io/fluentlabs-xyz/fluent-verifier:c5daa90c303892785f49cfdd9a42d147e22845cf
    container_name: fluent-verifier
    platform: linux/amd64
    depends_on:
      - backend
    ports:
      - "8089:8050"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - RUST_LOG=info
      - FLUENT_VERIFIER__DOCKER_API__NETWORK=developer-preview_default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
      - fluent_net

networks:
  default:
    name: blockscout2_default
  fluent_net:
    name: developer-preview_default
    external: true
