consensus:
  enabled: false
  url: "http://lighthouse:5052"
  name: "consensus-client"
execution:
  enabled: false
  url: "http://fluent:8545"
  name: "execution-client"
  modules:
    - "eth"
    - "net"
    - "web3"
    - "txpool"
    - "debug"
    - "trace"